= Yamba: Yet Another Micro Blogging App

We were looking for a perfect application to help you learn Android application development. Over the years, we've used different apps, everything from a Sudoku game to a restaurant and a golf application. While those were good, none of them was perfect.

We had two simple criteria for the learning app:

* Be comprehensive: the app has to cover most of the main building blocks of Android in a natural way, creating the motivation for various features that we want to demonstrate solutions for.
* Be ubiquitous: it should be easy to understand what the app does so that we can focus on building it and not explaining features.

The Twitter app has all those properties. Over the years we've been teaching Android development, Yamba has proven to be the perfect app to illustrate many different concepts. It has a nice way of also being flexible to extend in different directions. Some users are more focused on say UI features, while others want to understand architectural best practices and how various pieces communicate together. Yamba allows to taking the project into any of those directions and it provides for a nice framework to keep on building on top of.

We hope you enjoy the Yamba project. Happy hacking!

Marko